# Initializing Tensors

In [1]:
import torch

## Initializing Tensor

In [2]:
# Initializing Tensor
my_tensor = torch.tensor([[1,2,3],[4,5,6]])               # 2*3 tensor
my_tensor

tensor([[1, 2, 3],
        [4, 5, 6]])

In [3]:
my_tensor = torch.tensor([[1,2,3],[4,5,6]] , dtype = torch.float32)
my_tensor.dtype

torch.float32

In [4]:
# my_tensor = torch.tensor([[1,2,3],[4,5,6]], dtype = torch.float32, device = 'cuda')  #If GPU available
my_tensor = torch.tensor([[1,2,3],[4,5,6]] , dtype = torch.float32)                  #By default it is on 'cpu'

In [5]:
# Insted Of this we can directly assign device type like:
device = 'cuda' if torch.cuda.is_available() else 'cpu'
my_tensor = torch.tensor([[1,2,3],[4,5,6]] , dtype = torch.float32, device = device)
my_tensor.device

device(type='cpu')

In [6]:
my_tensor = torch.tensor([[1,2,3],[4,5,6]] , dtype = torch.float32, device = device, requires_grad = True)
# requires_grad is used to get gradientes in back-propagation
my_tensor.requires_grad

True

In [7]:
my_tensor.shape

torch.Size([2, 3])

## Other Initialization Methods

In [8]:
X = torch.empty((3,3))
X

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [9]:
X = torch.zeros((3,3))
X

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [10]:
X = torch.rand((3,3))
X

tensor([[0.7608, 0.4475, 0.2524],
        [0.4039, 0.4994, 0.9295],
        [0.2363, 0.1066, 0.4198]])

In [11]:
X = torch.ones((3,3))
X

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [12]:
X = torch.arange(start = 0, end = 10, step = 2 )
X

tensor([0, 2, 4, 6, 8])

In [13]:
X = torch.arange(10)       # By default start is 0 and step is 1
X

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [14]:
# eye(I) for Identity Tensor
X = torch.eye(4,4)      # Only single bracket
X

tensor([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.]])

In [15]:
# Get values bet two points
X = torch.linspace(start = 0.1, end = 1, steps = 10 )    # Here we use steps insted of step
X

tensor([0.1000, 0.2000, 0.3000, 0.4000, 0.5000, 0.6000, 0.7000, 0.8000, 0.9000,
        1.0000])

In [16]:
# Normal distribution
X = torch.empty((3,3)).normal_(mean = 0, std = 1)
X

tensor([[-0.2203, -0.5380,  1.6780],
        [ 0.1019,  0.2491,  0.9597],
        [ 0.0145, -0.3203, -0.3388]])

In [17]:
# Uniform distribution
X = torch.empty((3,3)).uniform_(0,1)
X

tensor([[0.1090, 0.8652, 0.8660],
        [0.1791, 0.3428, 0.6920],
        [0.0215, 0.9344, 0.9641]])

In [18]:
# Get diagonal elements
X = torch.diag(torch.rand((3,3)))
X

tensor([0.1608, 0.8041, 0.6180])

## Convert Tensor To other Dtype

In [19]:
# Convert it to bool type
our_tensor = torch.arange(5)
our_tensor.bool()
# 0,1,2,3,4

tensor([False,  True,  True,  True,  True])

In [20]:
our_tensor.short()
# int 16

tensor([0, 1, 2, 3, 4], dtype=torch.int16)

In [21]:
our_tensor.int()
# int 32

tensor([0, 1, 2, 3, 4], dtype=torch.int32)

In [22]:
our_tensor.long()
# int 64

tensor([0, 1, 2, 3, 4])

In [23]:
our_tensor.half()
# float 16

tensor([0., 1., 2., 3., 4.], dtype=torch.float16)

In [24]:
our_tensor.float()
# float 32

tensor([0., 1., 2., 3., 4.])

In [25]:
our_tensor.double()
# float 64

tensor([0., 1., 2., 3., 4.], dtype=torch.float64)

## Array to Tensor Conversion and vice versa

In [26]:
import numpy as np
my_array = np.array([1,2,3,4,5])
tensor_array = torch.from_numpy(my_array)
tensor_array 

tensor([1, 2, 3, 4, 5], dtype=torch.int32)

In [27]:
# Numpy array to tensor
array_tensor = tensor_array.numpy()
array_tensor

array([1, 2, 3, 4, 5])