# Tensor Operations

In [1]:
import torch
z1 = torch.tensor([2,4,6,8,9,15,7,0,1,11])
z2 = torch.tensor([1,3,5,6,7,11,4,2,9,10])

In [2]:
# add
z1 + z2
# or
torch.add(z1,z2)

tensor([ 3,  7, 11, 14, 16, 26, 11,  2, 10, 21])

In [3]:
# sub
z1 - z2
# or
torch.sub(z1,z2)

tensor([ 1,  1,  1,  2,  2,  4,  3, -2, -8,  1])

In [4]:
# div
z1 / z2
# or
torch.divide(z1,z2)
# or
torch.true_divide(z1,z2)

tensor([2.0000, 1.3333, 1.2000, 1.3333, 1.2857, 1.3636, 1.7500, 0.0000, 0.1111,
        1.1000])

In [5]:
# mul
z1 * z2
# or
torch.mul(z1,z2)
# or
torch.multiply(z1,z2)

tensor([  2,  12,  30,  48,  63, 165,  28,   0,   9, 110])

In [6]:
# **Importent**
# Inplace Operation
y = torch.empty(10) 
y += z1
y

# or

x = torch.empty(10)
x.add_(z1)

tensor([ 4.,  8., 12., 16., 18., 30., 14.,  0.,  2., 22.])

In [7]:
# Exponention

p = z1.pow(3)
p
# or
q = z1**3
q

tensor([   8,   64,  216,  512,  729, 3375,  343,    0,    1, 1331])

In [8]:
# **Importent**
# Matrix Multiplication
a1 = torch.rand((2,3))
a2 = torch.rand((3,4))
torch.mm(a1,a2)
# or
b = a1.mm(a2)
b

tensor([[0.5899, 1.1718, 1.2811, 0.5284],
        [0.6845, 1.1261, 1.1631, 0.4851]])

In [9]:
# Matrix Exponention
c = torch.rand((3,3))
c.matrix_power(3)

tensor([[1.9277, 0.5397, 1.0630],
        [1.0953, 0.3012, 0.6024],
        [1.9301, 0.5393, 1.0572]])

In [10]:
# Element wise multiplication
z1 * z2
# **Importent**
# Dot product
torch.dot(z1,z2)
# or
z1.dot(z2)

tensor(467)

In [11]:
# **Important**
# Broadcasting
m = torch.rand((5,5))
n = torch.rand((1,5))
# Here we can not substract or multiply n & m , as they have incompatible size
# But pytorch support Overloading i.e. n is subtracted from m 5 times
k1 = m - n 
k2 = m*n
k1,k2

(tensor([[ 0.0593,  0.0918, -0.3587, -0.1733, -0.1800],
         [-0.2942, -0.7819,  0.0555, -0.2086,  0.1548],
         [-0.5944, -0.8465,  0.0645, -0.2921,  0.5024],
         [ 0.1783, -0.5360, -0.1148, -0.8899,  0.1237],
         [-0.5267, -0.6196, -0.7582,  0.0305, -0.2767]]),
 tensor([[0.4371, 0.9081, 0.3430, 0.7675, 0.1155],
         [0.2136, 0.1147, 0.6709, 0.7333, 0.2633],
         [0.0239, 0.0560, 0.6781, 0.6527, 0.4167],
         [0.5123, 0.3380, 0.5361, 0.0746, 0.2495],
         [0.0666, 0.2620, 0.0266, 0.9646, 0.0728]]))

In [12]:
# Other Inbuilt Operations
maxn,ids = torch.max(z1,dim=0)
maxn,ids

(tensor(15), tensor(5))

In [13]:
minn,ids = torch.min(z1,dim=0)
minn,ids

(tensor(0), tensor(7))

In [14]:
# absolute value
torch.abs(z1-z2)

tensor([1, 1, 1, 2, 2, 4, 3, 2, 8, 1])

In [15]:
# **Importent**
torch.argmax(z1,dim = 0)

tensor(5)

In [16]:
# ***Importent***
torch.mean(z1.float())
# We have to use float() to get mean

tensor(6.3000)

In [17]:
# ****Importent****
# Compare
z1.eq(z2)

tensor([False, False, False, False, False, False, False, False, False, False])

In [18]:
# ****Importent*****
# Sorting
torch.sort(z1)

torch.return_types.sort(
values=tensor([ 0,  1,  2,  4,  6,  7,  8,  9, 11, 15]),
indices=tensor([7, 8, 0, 1, 2, 6, 3, 4, 9, 5]))

In [19]:
# ******Importent*****
# Clamp method: used to calculate range between two numbers
atleast5 = torch.clamp(z1 , min = 5)
atmost8 = torch.clamp(z1 , max =8)
btn5n8 = torch.clamp(z1 , min = 5,max = 8)
atleast5,atmost8,btn5n8

(tensor([ 5,  5,  6,  8,  9, 15,  7,  5,  5, 11]),
 tensor([2, 4, 6, 8, 8, 8, 7, 0, 1, 8]),
 tensor([5, 5, 6, 8, 8, 8, 7, 5, 5, 8]))

In [20]:
# **********Importent*******
# Any & all methods
# Any:return when at leats one is true
# All:return when all the values are true
x1 = torch.tensor([1,1,1,0,1], dtype = torch.bool)
torch.any(x1),torch.all(x1)

(tensor(True), tensor(False))