## Torch Indexing

In [1]:
import torch

In [2]:
batch = 10
features = 25
X = torch.rand((batch,features))
X[: ,0]
# First entry of all batches
X[0,:]
# first batch all features

tensor([0.0331, 0.8582, 0.8786, 0.3985, 0.9973, 0.4052, 0.0275, 0.9179, 0.8511,
        0.9617, 0.5517, 0.6474, 0.4110, 0.7831, 0.3858, 0.4562, 0.7717, 0.8529,
        0.1183, 0.2040, 0.2271, 0.7015, 0.5996, 0.0285, 0.5809])

In [3]:
# Fancy Indexing
Y = torch.rand((3,4))
row = torch.tensor((2,0))
col = torch.tensor((3,1))
Y,Y[row,col]
# Here we got elements at 2,3 and 0,1

(tensor([[0.4004, 0.3961, 0.2122, 0.5226],
         [0.0451, 0.2800, 0.2798, 0.6967],
         [0.3067, 0.7027, 0.1800, 0.9430]]),
 tensor([0.9430, 0.3961]))

In [4]:
Z = torch.rand(10)
indices = [2,5,8]
Z[indices]

tensor([0.1977, 0.0542, 0.2777])

In [5]:
# Get values from tensor with some condition
T = torch.tensor([1,2,6,8,7,5,4,3,9,0])
T[T > 5]

tensor([6, 8, 7, 9])

In [6]:
T[(T > 3) & (T < 8) ]

tensor([6, 7, 5, 4])

In [7]:
T[T.remainder(2) == 0]

tensor([2, 6, 8, 4, 0])

In [8]:
# ****VIMP****
# Where Operation: where(condition,printIFtrue,printIFfalse)
torch.where(T>5,T,2*T)
# print T if > 5 else print its double

tensor([ 2,  4,  6,  8,  7, 10,  8,  6,  9,  0])

In [9]:
# Get unique values
H = torch.tensor([0,1,1,0,2,3,4,4,2,1])
H.unique()

tensor([0, 1, 2, 3, 4])

In [10]:
K = torch.Tensor([[1,2,3],[2,3,4],[4,5,6]])
K.ndimension()
# 2D

2