## Tensor Reshaping

In [1]:
import torch
Z = torch.tensor([1,2,3,4,5,6,7,8,9,10])
Z.shape

torch.Size([10])

In [2]:
P = Z.view((5,2))
# Remember that both tensors have same number of values
# Here values are 10 in both the tensors

In [3]:
P.shape

torch.Size([5, 2])

In [4]:
P.reshape([1,10])

tensor([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10]])

In [5]:
# **IMP**
# View Vs Reshape
# View work on contiguous Tensors memory
# Reshape woek on both memory allocations

In [6]:
# Transpose of Tensors
A = torch.tensor([[1,2,3],[4,5,6],[7,8,9]])
A , A.t()

(tensor([[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]),
 tensor([[1, 4, 7],
         [2, 5, 8],
         [3, 6, 9]]))

In [7]:
B = A.t()
B.view((1,9))
# We can not reshape transpose directly

RuntimeError: view size is not compatible with input tensor's size and stride (at least one dimension spans across two contiguous subspaces). Use .reshape(...) instead.

In [8]:
B.contiguous().view((1,9))
# We use Contiguous() before view to reshape tensors

tensor([[1, 4, 7, 2, 5, 8, 3, 6, 9]])

In [9]:
# ***IMP***
# Concatination of two tensors
x1 = torch.tensor([2,4,6,8,0])
x2 = torch.tensor([1,3,5,7,9])
X = torch.cat((x1,x2))
X

tensor([2, 4, 6, 8, 0, 1, 3, 5, 7, 9])

In [10]:
X.sort()

torch.return_types.sort(
values=tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]),
indices=tensor([4, 5, 0, 6, 1, 7, 2, 8, 3, 9]))

In [11]:
# Convert into 1D array using -1
U = torch.rand((3,2))
U, U.view(-1)

(tensor([[0.2313, 0.8604],
         [0.7933, 0.3438],
         [0.5652, 0.2815]]),
 tensor([0.2313, 0.8604, 0.7933, 0.3438, 0.5652, 0.2815]))

In [12]:
print(U,U.shape)
print(U.unsqueeze(0),U.unsqueeze(0).shape)
print(U.unsqueeze(1),U.unsqueeze(1).shape)
print(U.unsqueeze(2),U.unsqueeze(2).shape)
# Add one extra dimention at required position 0: 1st position ,1: 2nd position....

tensor([[0.2313, 0.8604],
        [0.7933, 0.3438],
        [0.5652, 0.2815]]) torch.Size([3, 2])
tensor([[[0.2313, 0.8604],
         [0.7933, 0.3438],
         [0.5652, 0.2815]]]) torch.Size([1, 3, 2])
tensor([[[0.2313, 0.8604]],

        [[0.7933, 0.3438]],

        [[0.5652, 0.2815]]]) torch.Size([3, 1, 2])
tensor([[[0.2313],
         [0.8604]],

        [[0.7933],
         [0.3438]],

        [[0.5652],
         [0.2815]]]) torch.Size([3, 2, 1])
